Fix lint in arrow-flight by updating assert_cmd after it upgraded (#8741)
This is currently causing clippy lint to fail on the arrow-flight crate,
see e.g.
https://github.com/apache/arrow-rs/actions/runs/18908499021/job/53972604621

Clippy says
```
error: use of deprecated associated function `assert_cmd::Command::cargo_bin`: incompatible with a custom cargo build-dir, see instead `cargo::cargo_bin_cmd!`
   --> arrow-flight/tests/flight_sql_client_cli.rs:256:18
    |
256 |         Command::cargo_bin("flight_sql_client")
```

---------

Co-authored-by: Andrew Lamb <andrew@nerdnetworks.org>