Remove dead code to fix clippy failure on main (#9215)
# Which issue does this PR close?


# Rationale for this change
Clippy is failing on main:
https://github.com/apache/arrow-rs/actions/runs/21112104909/job/60712213339


```
error: function `get_offsets` is never used
   --> arrow-array/src/array/mod.rs:929:11
    |
929 | unsafe fn get_offsets<O: ArrowNativeType>(data: &ArrayData) -> OffsetBuffer<O> {
    |           ^^^^^^^^^^^
    |
    = note: `-D dead-code` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(dead_code)]`

```

This is due to a logical conflict with some of my PRs (that migrated to
use a different version of this function, and now this one is not used)

# What changes are included in this PR?

remove the unused method

# Are these changes tested?


# Are there any user-facing changes?

<!--
If there are user-facing changes then we may require documentation to be
updated before approving the PR.

If there are any breaking changes to public APIs, please call them out.
-->