fix: `rustdoc::unportable_markdown` was removed
Nightly CI fails with:

```text
  Documenting arrow-flight v55.0.0 (/__w/arrow-rs/arrow-rs/arrow-flight)
error: lint `rustdoc::unportable_markdown` has been removed: old parser removed
  --> arrow-flight/src/sql/mod.rs:48:14
   |
48 |     #![allow(rustdoc::unportable_markdown)]
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `-D renamed-and-removed-lints` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(renamed_and_removed_lints)]`

error: could not document `arrow-flight`
```

due to https://github.com/rust-lang/rust/pull/140709 .