chore: Silence clippy warning about `get_encoder` (#11436)
# Which issue does this PR close?

None

# Rationale for this change

#11051 removed some usage of the experimental
`parquet::encodings::encoding::get_encoder` function. This causes a
clippy dead code warning when running with the `--workspace` argument as
suggested in `CONTRIBUTING.md`. CI tests instead run with `-p parquet`
which does not trigger the dead code warning.

```
% cargo clippy --workspace --all-targets --all-features -- -D warnings
    Blocking waiting for file lock on build directory
    Checking parquet v60.0.0 (/Users/seidl2/src/arrow-rs/parquet)
error: function `get_encoder` is never used
  --> parquet/src/encodings/encoding/mod.rs:88:8
   |
88 | pub fn get_encoder<T: DataType>(
   |        ^^^^^^^^^^^
   |
   = note: `-D dead-code` implied by `-D warnings`
   = help: to override `-D warnings` add `#[expect(dead_code)]` or `#[allow(dead_code)]`

error: could not compile `parquet` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

```
% cargo clippy -p parquet --all-targets --all-features -- -D warnings
    Checking parquet v60.0.0 (/Users/seidl2/src/arrow-rs/parquet)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 15.49s
```

# What changes are included in this PR?

Selectively ignore the dead code warning.

# Are these changes tested?

N/A

# Are there any significant user-facing changes?

No