fix: include chrono-tz in flight sql cli (#6650)
Otherwise you get an error like:

```text
Error: format results

Caused by:
    Parser error: Invalid timezone \"Europe/Berlin\": only offset based timezones supported without chrono-tz feature
```