fix main: parquet test compilation failure (#10266)
audit failing

```sh
Crate:     quick-xml
Version:   0.39.3
Title:     Unbounded namespace-declaration allocation in `NsReader` enables memory-exhaustion denial of service
Date:      2026-06-29
ID:        RUSTSEC-2026-0195
URL:       https://rustsec.org/advisories/RUSTSEC-2026-0195
Severity:  7.5 (high)
Solution:  Upgrade to >=0.41.0
```

parquet test failing

```sh
error[E0061]: this function takes 6 arguments but 5 arguments were supplied
   --> parquet/src/arrow/arrow_reader/read_plan.rs:544:20
    |
544 |         let leaf = make_int32_page_reader(&data, &levels, &levels, 0, 0);
    |                    ^^^^^^^^^^^^^^^^^^^^^^------------------------------- argument #6 of type `Option<i16>` is missing
    |
note: function defined here
   --> parquet/src/arrow/array_reader/test_util.rs:102:8
    |
102 | pub fn make_int32_page_reader(
    |        ^^^^^^^^^^^^^^^^^^^^^^
...
108 |     padding_threshold: Option<i16>,
    |     ------------------------------
help: provide the argument
    |
544 |         let leaf = make_int32_page_reader(&data, &levels, &levels, 0, 0, /* Option<i16> */);
    |                                                                        +++++++++++++++++++

error[E0061]: this function takes 6 arguments but 5 arguments were supplied
   --> parquet/src/arrow/arrow_reader/read_plan.rs:550:29
    |
550 |         let struct_reader = StructArrayReader::new(struct_type, vec![leaf], 0, 0, false);
    |                             ^^^^^^^^^^^^^^^^^^^^^^-------------------------------------- argument #6 of type `Option<i16>` is missing
    |
note: associated function defined here
   --> parquet/src/arrow/array_reader/struct_array.rs:42:12
    |
 42 |     pub fn new(
    |            ^^^
...
 48 |         padding_threshold: Option<i16>,
    |         ------------------------------
help: provide the argument
    |
550 |         let struct_reader = StructArrayReader::new(struct_type, vec![leaf], 0, 0, false, /* Option<i16> */);
    |                                                                                        +++++++++++++++++++
```