[56_maintenance] Fix cargo_audit: Pin cargo-msrv and Cargo.lock in CI (#9902)
NOTE: almost all of this PR is `Cargo.lock` files. I swear it is easy to
review...

- Part of https://github.com/apache/arrow-rs/issues/9857
- Follow-up to https://github.com/apache/arrow-rs/pull/9896

# Rationale

The MSRV check is failing on 56 (I saw on
https://github.com/apache/arrow-rs/pull/989) due to the fact that many
of arrow's dependencies have upgraded to a newer version of rust that
has a newer MSRV.

Here is an example CI fail
https://github.com/apache/arrow-rs/actions/runs/25373570591/job/74402867748?pr=9896

```
  Run if which cargo-msrv ; then echo "using existing cargo-msrv binary" ; else cargo
  install cargo-msrv ; fi
    if which cargo-msrv ; then echo "using existing cargo-msrv binary" ; else cargo install
  cargo-msrv ; fi
    shell: sh -e {0}
    env:
      RUSTFLAGS: -C debuginfo=1
      RUST_BACKTRACE: 1
      Updating crates.io index
  error: cannot install package `cargo-msrv 0.19.3`, it requires rustc 1.91.1 or newer,
  while the currently active rustc version is 1.89.0
  `cargo-msrv 0.18.4` supports rustc 1.85
  Error: Process completed with exit code 101.
```

This PR:
- Pins `cargo-msrv` in the `56_maintenance` MSRV CI job to a version
compatible with the Rust toolchain used by the job
- Checks in a Cargo.lock file so the older versions of the crate still
run

Note this doesn't actually change any code in this crate. It simply
updates the CI enough to get the tests to pass