Minor: fix clippy after logical conflict (#7803)
# Which issue does this PR close?

We generally require a GitHub issue to be filed for all bug fixes and
enhancements and this helps us generate change logs for our releases.
You can link an issue to this PR using the GitHub syntax.

- Follow on to https://github.com/apache/arrow-rs/pull/7757

# Rationale for this change

Clippy is failing after merging
https://github.com/apache/arrow-rs/pull/7757 due to a logical conflict
and a new clippy release:


https://github.com/apache/arrow-rs/actions/runs/15924256410/job/44917809525

```
error: variables can be used directly in the `format!` string
   --> parquet-variant/src/variant/list.rs:130:25
    |
130 |             Err(err) => panic!("validation error: {}", err),
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args
    = note: `-D clippy::uninlined-format-args` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::uninlined_format_args)]`
help: change this to
    |
1[30](https://github.com/apache/arrow-rs/actions/runs/15924256410/job/44917809525#step:6:31) -             Err(err) => panic!("validation error: {}", err),
130 +             Err(err) => panic!("validation error: {err}"),
    |
```

# What changes are included in this PR?

Fix clippy to get CI clean on main

# Are these changes tested?
By CI

# Are there any user-facing changes?

No