json feature always requires base64 feature
It should fix build failure when only json feature is enabled.

```
% cargo build --no-default-features --features json
error[E0433]: failed to resolve: use of undeclared crate or module `base64`
   --> parquet/src/record/api.rs:691:46
    |
691 |             Field::Bytes(b) => Value::String(base64::encode(b.data())),
    |                                              ^^^^^^ use of undeclared crate or module `base64`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `parquet` due to previous error
```