fix: enable TLS roots for flight CLI client
Otherwise you get:

```text
Error: setup client

Caused by:
    0: connect to endpoint
    1: transport error
    2: invalid peer certificate: UnknownIssuer
    3: invalid peer certificate: UnknownIssuer
```

Also see https://github.com/hyperium/tonic/issues/1904 .