feat: improve flight CLI error handling (#4873)
**Before:**

```text
thread 'main' panicked at 'collect data stream: Status { code: Internal, message: "h2 protocol error: error reading a body from connection: stream error received: unexpected internal error encountered", source: Some(hyper::Error(Body, Error { kind: Reset(S
treamId(3), INTERNAL_ERROR, Remote) })) }', arrow-flight/src/bin/flight_sql_client.rs:130:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**After:**

```text
Error: read flight data

Caused by:
    0: collect data stream
    1: status: Internal, message: "h2 protocol error: error reading a body from connection: stream error received: unexpected internal error encountered", details: [], metadata: MetadataMap { headers: {} }
    2: error reading a body from connection: stream error received: unexpected internal error encountered
    3: stream error received: unexpected internal error encountered
```